FROM centos:7

LABEL liubaicai "liushuai.baicai@hotmail.com"

RUN yum install -y vim git net-tools openssh-server && \
    ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

WORKDIR /root
COPY entrypoint_centos.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
